name: library_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  flutter_bloc: ^8.1.3
  go_router: ^10.0.0
  flutter_screenutil: ^5.8.4
  flutter_native_splash: ^2.3.1
  dio: ^5.4.0
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  flutter_tabler_icons: ^1.2.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  mesh_gradient: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/translations/